### PR TITLE
[mongodb] handle null options

### LINKED ISSUE #136: Mongoose passing `null` options crashes instrumentation in prefixKeys
In what may have been a recent update, Mongoose is passing `null` into the MongoDB API for the options to `insertOne` and others, which is tripping up the Beeline instrumentation.

You can see the troublesome Mongoose code here: https://github.com/Automattic/mongoose/blob/5.4.22/lib/model.js#L242

This `null` then makes it way into `prefixKeys` and crashes here: https://github.com/honeycombio/beeline-nodejs/blob/master/lib/instrumentation/mongodb.js#L8

I have fixed this locally by changing `Object.keys(map)` to `Object.keys(map || {})` but there may be a more appropriate fix.

### PR DESCRIPTION
**Pull request by toshok**
Fixes #136 

Change `prefixKeys` from defaulting the `map` parameter to `{}` (which only works when the argument is `undefined`) and instead guard around the `addContext("db.options", options)` call.

This means that `additionalContext` callbacks _must_ return an object if present (which they all do).

### CODE REVIEW

File: lib/instrumentation/mongodb.js [hunk 1]
```diff
@@ -48,7 +48,9 @@ function instrumentMongodb(mongodb, opts = {}) {
             [schema.TRACE_SPAN_NAME]: eventName,
           },
           span => {
-            api.addContext(prefixKeys("db.options", options));
+            if (options) {
```
Comment (toshok) [inline lib/instrumentation/mongodb.js]: this and line 6 above are the only code changes.  the rest are thanks to `prettier`.

**Comment by SeanHood** [comment]
Hi, wondering if any more progress has been made on this issue? We have had to disable mongodb instrumentation for now in our app. Loving Honeycomb for everything else though 👌

**Comment by toshok** [comment]
> makes sense to me.
> 
> Did you consider adding the guard in `prefixKeys`? wrap it in an `if(map)` then checking the output before adding calling `addContext`? It seems like it might be a safer option for callers of `prefixKeys`

done
